Add C# code blocks to the Using JSON guide
thoth-tech/splashkit.io-starlight pull request #133
Opened 2024-08-01 06:58 UTC by Srainyyyy

Add C# code blocks to the three existing JSON guides to provide equivalent examples for C# developers

2024-08-04 06:50 UTC, ShaunR1991 commented on src/content/docs/guides/json/0-json_intro.mdx
> +
Need to check the functions you are using as they do not exist.

The below compiles and runs when game_data.json exists in the Resource/json folder within your project:

using SplashKitSDK;

class JsonTutorial
{
    static void Main()
    {
        Json gameData;
        gameData = SplashKit.JsonFromFile("game_data.json");
        string gameTitle = SplashKit.JsonReadString(gameData, "gameTitle");
        
        SplashKit.WriteLine("Game Title: " + gameTitle);
        
        SplashKit.FreeJson(gameData);
    }
}

2024-08-04 06:51 UTC, ShaunR1991 commented on src/content/docs/guides/json/0-json_intro.mdx
> +
As above, this code does not compile correctly. 

See below:

```
using SplashKitSDK;

class JsonTutorial
{
    static void Main()
    {
        Json gameData;
        gameData = SplashKit.JsonFromFile("game_data.json");

        if(SplashKit.JsonHasKey(gameData, "gameTitle"))
        {
            string gameTitle = SplashKit.JsonReadString(gameData, "gameTitle");
            SplashKit.WriteLine("Game Title: " + gameTitle);
        }
        else
        {
            SplashKit.WriteLine("Key \"gameTitle\" not found.");
        }

        SplashKit.FreeJson(gameData);
    }
}
```

2024-08-04 07:09 UTC, ShaunR1991 commented on src/content/docs/guides/json/1-json_reading.mdx
> +  var levels = new List<string>();
Recommend:

`List<string> levels = new List<string>();`

2024-08-04 07:09 UTC, ShaunR1991 commented on src/content/docs/guides/json/1-json_reading.mdx
> +  SplashKit.FreeJson(gameData);
Recommend removing this to be in line with the C++ code.

2024-08-04 07:10 UTC, ShaunR1991 commented on src/content/docs/guides/json/1-json_reading.mdx
> +  Json gameScreenSize = SplashKit.JsonReadObject(game_data, "screenSize");
Change the Json variable from game_data to gameData.

2024-08-04 07:15 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  var newGameData = Json.Create();
These functions do not exist. 

See below:

Json newGameData = SplashKit.CreateJson();
SplashKit.JsonSetString(newGameData, "gameTitle", "My New Game");
SplashKit.JsonSetBool(newGameData, "fullScreenMode", false);
SplashKit.JsonSetNumber(newGameData, "numPlayers", 1);

2024-08-04 07:18 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  var levelsArray = new List<string>
Function does not exist. See below:

```
List<string> levelsArray = new List<string>
    {
        "level1",
        "level2",
        "level3"
	};

SplashKit.JsonSetArray(newGameData, "levels", levelsArray);
```

2024-08-04 07:23 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  var screenSizeData = Json.Create();
Functions do not exist. See below:

```
Json screenSizeData = SplashKit.CreateJson();

SplashKit.JsonSetNumber(screenSizeData, "width", 800);
SplashKit.JsonSetNumber(screenSizeData, "height", 600);

SplashKit.JsonSetObject(newGameData, "screenSize", screenSizeData);
```

2024-08-04 07:24 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  newGameData.ToFile("new_game_data.json");
Function does not exist. See below:

`SplashKit.JsonToFile(newGameData, "new_game_data.json");`

2024-08-04 07:25 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  ```csharp
See above comments and adjust code to ensure these are using the correct C# functions.

2024-08-04 07:26 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  var playerData = Json.Create();
As above - check that these are the correct C# functions.

2024-08-04 07:26 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  var existingData = Json.FromFile("new_game_data.json");
As above - check that these are the correct C# functions.

2024-08-04 07:26 UTC, ShaunR1991 commented on src/content/docs/guides/json/2-json_writing.mdx
> +  var modifiedGameData = Json.FromFile("modified_game_data.json");
As above - check that these are the correct C# functions.

2024-08-04 07:27 UTC, ShaunR1991 reviewed
This code needs to be re-done as very many of these functions are not the correct C# functions and thus the code will not compile. Ensure code is tested before reuploading.

2024-08-04 23:38 UTC, ShaunR1991 approved these changes
All code compiles and is the C# facsimile of the C++ code. Looks good!

2024-08-09 04:12 UTC, s223126445 approved these changes
All Codes were running. Used the top-level statements in C# code and maintained the structure as C++.
![yang1](https://github.com/user-attachments/assets/fe2e90ad-93bd-4a6f-ac8f-1c17d8fa1131)
![yang2](https://github.com/user-attachments/assets/065a1a61-e7d3-4307-a650-e890c8a568d5)
![yang3](https://github.com/user-attachments/assets/f16393de-04c0-4484-b946-799f729e44dc)
![yang4](https://github.com/user-attachments/assets/188ab995-07a2-44cf-b5b8-bbceb73e62cf)

2024-08-13 09:06 UTC, omckeon requested changes
For all code blocks:

Please add `using static SplashKitSDK.SplashKit;` below line 1.

Then remove all the `SplashKit.` parts of the code.

2024-08-14 03:58 UTC, omckeon approved these changes
Thank you for these updates. Code blocks look great now!

2024-08-14 05:28 UTC, merged

2024-08-14 05:29 UTC, omckeon commented
Have merged this now, and will merge it upstream as well :)

Just wanted to note that for future pull requests, make sure you have created a new branch to add the changes into, rather than to main. And make sure to pull the changes from upstream into your fork as well :)