Review "splashkit camera" guide
thoth-tech/splashkit.io-starlight pull request #164
Opened 2024-09-03 04:08 UTC by Srainyyyy

A tutorial review of this tutorial has been completed. You have run the code in this tutorial to ensure that it works properly and outputs the results. Fixed an issue in Python code where the wrong number of parameters were passed when fill_rectangle() was called, removed extra parameters, made sure that C# used a top-level statement style, and made sure that the style was consistent with other languages, changed some text descriptions to more clearly express the relationship between game coordinates and screen coordinates, And how to achieve dynamic effects through camera movement.

## Confirmation of Passing Quality Checks:

- [x] The tutorial is free of spelling and grammatical errors.
- [x] The tutorial is easy to follow.
- [x] The tutorial has:
  - [x] C# using top level statements
  - [x] C++
  - [x] Python
- [x] The code passes all the Quality Checks.

## Code test screenshot
C++
![image](https://github.com/user-attachments/assets/2e485c98-2d75-4cb7-ad3b-b2fa3afb3ecf)
C#
![image](https://github.com/user-attachments/assets/7e444d93-8bdb-4409-9cd2-452402e5fb8b)
Python
![image](https://github.com/user-attachments/assets/d7190c33-f621-41f9-8b5c-283c9e687c03)

2024-09-09 00:12 UTC, breezy-codes commented
I've reviewed the program code and it all runs correctly:

## C++
![cpp](https://github.com/user-attachments/assets/54fa4280-f35c-40ee-805a-bd5eae3cfbd1)

## C#
![c#](https://github.com/user-attachments/assets/0f2751fd-2196-41b8-a30c-190d3a4070d7)

## Python
![python](https://github.com/user-attachments/assets/44290b17-2a84-4ce9-94a7-3484c91230bc)

2024-09-09 00:14 UTC, breezy-codes requested changes

2024-09-09 00:14 UTC, breezy-codes commented on src/content/docs/guides/Camera/0-using-splashkit-camera.mdx
> +lastupdated: 3 SEP 2024
Change it to be "Sep" to match in with how this is shown in the other guides.

2024-09-09 04:01 UTC, breezy-codes approved these changes
All changes fixed. Good job.

2024-09-20 07:41 UTC, Jinx-means-jinx commented on src/content/docs/guides/Camera/0-using-splashkit-camera.mdx
> +lastupdated: 3 Sep 2024
It is better to write like Sep 3, 2024

2024-09-21 03:12 UTC, Jinx-means-jinx approved these changes

2024-10-09 08:13 UTC, merged