usage example for sprite set position
thoth-tech/splashkit.io-starlight pull request #168
Opened 2024-09-05 11:25 UTC by kay-kaushik

# Description
This pull request features usage exaples for sprite_set_position(). The usage example is clear and concise to help the user understand how to implement the function.

# Features
+ clear and concise code
+ gifs
+ images
+ perfect example

# Changes
5 files have been added. 2 code, 1 text and 1 png file and 1 gif.

# Benefits
These high quality usage examples give more context to the functions. This will help users reading the documentation to better understand the function. This will result in faster development.

# Testing
All the changes have been tested on Kartik Kaushik's system

# Testing Images

![image](https://github.com/user-attachments/assets/6f446188-1530-408e-9901-9bb6b273fa7d)

2024-09-10 04:45 UTC, omckeon requested changes
Just need to update a few things mentioned in the comments

2024-09-10 04:47 UTC, omckeon commented
Make sure you have run `npm run build` successfully as well. (The check should not be failing.)

2024-09-25 13:20 UTC, kay-kaushik commented on src/assets/usage-examples-code/sprites/sprite_set_position/sprite_set_position-9-sprite-s-pos.txt
> +### sprite_set_position() usage example
I have made the changes

2024-09-25 13:21 UTC, kay-kaushik commented on public/usage-examples-images-gifs/sprites/protSpriteSheet-R.png
Done

2024-09-25 13:21 UTC, kay-kaushik commented on src/assets/usage-examples-code/sprites/sprite_set_position/sprite_set_position-9-sprite-s-pos.txt
> +The following code is an example of using sprite set position which sets the new x and y position of a sprite on a splashkit window.
I have done as asked.

2024-09-26 04:33 UTC, NidhishaPahade reviewed
Everything looks good  to me.

2024-10-09 04:52 UTC, merged