WSL automated installation script for programmers guide
thoth-tech/splashkit.io-starlight pull request #17
Opened 2024-04-22 08:27 UTC by SatyamRaina

# Pull Request Description:

This pull request introduces a comprehensive script designed to automate the installation process of Windows Subsystem for Linux (WSL) along with essential dependencies required for development. The script includes the installation of SplashKit, .NET, Visual Studio Code, and language-specific tools to streamline the setup process for developers.

## Key Features:
- Automated installation of WSL, including necessary components and configurations.
- Installation of SplashKit for graphics and multimedia development.
- Integration of .NET framework for building cross-platform applications.
- Setup of Visual Studio Code with recommended extensions for a seamless coding experience.
- Inclusion of language tools for enhanced development capabilities.

This script aims to simplify the initial setup for developers by reducing manual steps and ensuring a consistent development environment across systems. Feedback and contributions are welcome to improve functionality and expand compatibility.

2024-04-22 08:59 UTC, hugglesfox commented
Is this PR meant to change 133 files?

If so then it might be nice to split it into multiple commits. If that's not the intention and you need some help fixing the commit, feel free to message me on teams and we can sort it out

2024-05-03 08:01 UTC, omckeon requested changes
I've just tested this script on my Windows laptop. Everything works well except that we don't want to install VS Code in WSL - instead, the user will be using VS Code on Windows, and then will install the WSL extension to connect in with WSL.

2024-05-03 08:02 UTC, omckeon commented on scripts/demo.sh
> +# Install VS Code
Remove lines 40 - 45 (Not needed for WSL)

2024-05-03 08:08 UTC, omckeon commented on scripts/demo.sh
> +
Missing a few extensions here. Update this part to be:

code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.vscodeintellicode-csharp

2024-05-03 08:12 UTC, omckeon commented
Can you make a new PR to add the updated script into a folder named 'wsl' in this repo: https://github.com/thoth-tech/skm/tree/develop/install-scripts. And name the file 'wsl-install.sh'.

2024-05-03 08:14 UTC, omckeon commented
Closing this PR as it should just be for the script. The other changes should go into a separate PR.

2024-05-03 08:14 UTC, closed without merging