Introduction to json tutorial c# language update
thoth-tech/splashkit.io-starlight pull request #175
Opened 2024-09-09 04:10 UTC by Srainyyyy

I have added C# OOP code to this tutorial, below is a screenshot of the code test：
![image](https://github.com/user-attachments/assets/a0f751b2-7156-48c9-a15b-93d5028d8739)
![image](https://github.com/user-attachments/assets/7f9e9c88-3c6f-4cfc-9b32-646a4c68042d)

2024-09-12 05:12 UTC, s223126445 approved these changes
Tutorial Review - Introduction to json tutorial c# language update
 Good work, both the codes are working fine.But please update the OOP code similar to the top-level statement.
Screenshots of code test:
![Opp_test1](https://github.com/user-attachments/assets/25db80c2-ea1e-4951-800a-10b76e83fdbd)
![OOP_test2](https://github.com/user-attachments/assets/83b09eac-5156-4f5d-85a5-5b64d60d06e4)

2024-09-16 06:46 UTC, breezy-codes commented on src/content/docs/guides/JSON/0-json_intro.mdx
> +            // Define the file path
I would remove these comments in the OOP version as there is no comments in the C++ or the C# top level statement version. So the comments within this OOP one look really out of place.

2024-09-16 06:46 UTC, breezy-codes commented on src/content/docs/guides/JSON/0-json_intro.mdx
> +            // Define the file path
Similar in this one, the comments look out of place when comparing to the C++ and C# top level statement versions.

2024-09-16 06:47 UTC, breezy-codes requested changes
The code runs correctly and looks good, although the comments within the code need to be removed so that they match with how the code is in the C++ and C# top level versions.

2024-09-16 06:57 UTC, breezy-codes approved these changes
Looks great now, everything works correctly.

2024-10-01 07:04 UTC, merged