Added Language Updates
thoth-tech/splashkit.io-starlight pull request #197
Opened 2024-09-20 13:56 UTC by NidhishaPahade

<img width="1127" alt="Screenshot 2024-09-20 192324" src="https://github.com/user-attachments/assets/1ddacb78-7897-4fdd-add6-4844d7f38c3f">
<img width="1127" alt="Screenshot 2024-09-20 193150" src="https://github.com/user-attachments/assets/d1ca767e-492e-480e-9b1e-b3c8079aa498">

2024-09-22 03:48 UTC, omckeon commented
This guide actually didn't have any code for it, so will also need the C++ tabs.

2024-09-22 03:48 UTC, omckeon commented
@NidhishaPahade I have now updated the files as I had suggested on Teams.

Please update the PR description to use the template from [this page](https://thoth-tech.netlify.app/products/splashkit/splashkit-tutorials/onboarding/04-pull-request-template/). With screenshots put at the end.

2024-09-26 02:50 UTC, oliverexell-bruce requested changes
Line 108, `window.CloseRequested("Double Buffering")` should be `window.CloseRequested`

2024-09-26 04:25 UTC, oliverexell-bruce approved these changes
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

- [X] Tested in latest Chrome
- [X] Tested in latest Firefox
- [X] npm run build
- [X] npm run preview

## Folders and Files Added/Modified

Please list the folders and files added/modified with this pull request.

- Added:
  - [X] N/A
- Modified:
  - [X] src/content/docs/guides/Graphics/1-double-buffering.mdx

Looks good, great work!

2024-09-26 06:21 UTC, kay-kaushik approved these changes
The code looks clean and is easy to understand. I know you just did the c# code but there is a spelling mistake which I pointed out, Fix that and it all looks good.

2024-09-26 06:21 UTC, kay-kaushik commented on src/content/docs/guides/Graphics/1-double-buffering.mdx
>  1. Anything you draw will not appear unit you have refreshed the screen
here until has a speling mistake, its written as unit

2024-10-01 05:34 UTC, omckeon commented
This tutorial guide originally did not have any code so good work creating some example code. However, as this code doesn't relate to the content of the guide above (House drawing), and is missing the C++ tab, I will close this PR.
The closing of this PR won't affect your portfolio though.

2024-10-01 05:34 UTC, closed without merging