Added Language Updates
thoth-tech/splashkit.io-starlight pull request #200
Opened 2024-09-20 13:59 UTC by NidhishaPahade

![Uploading Screenshot 2024-09-20 202852.png…]()

2024-09-22 03:55 UTC, omckeon commented
@NidhishaPahade Please update the PR description to use the template from [this page](https://thoth-tech.netlify.app/products/splashkit/splashkit-tutorials/onboarding/04-pull-request-template/). With screenshots put at the end.

2024-09-23 03:47 UTC, omckeon requested changes
Great work overall @NidhishaPahade !

Just a few things to update in the line comments. You can then use this information to check the other similar PRs you have open. :)

2024-09-23 03:47 UTC, omckeon commented on src/content/docs/guides/Interface/02-interface-styling.mdx
> +    CloseAllWindows();
Reduce the indentation of these lines by 1 tab.

2024-09-23 03:47 UTC, omckeon commented on src/content/docs/guides/Interface/02-interface-styling.mdx
> + using SplashKitSDK;
Is this line needed? I don't think it will be needed.

2024-09-23 03:47 UTC, omckeon commented on src/content/docs/guides/Interface/02-interface-styling.mdx
> +                SplashKit.ClearScreen(Color.White);
You could update this line to `window.Clear(Color.White)`

2024-09-23 03:47 UTC, omckeon commented on src/content/docs/guides/Interface/02-interface-styling.mdx
> +                SplashKit.RefreshScreen();
You could update this line to `window.Refresh()`

2024-09-23 03:47 UTC, omckeon commented on src/content/docs/guides/Interface/02-interface-styling.mdx
> +    SetInterfaceFontSize(12);
Reduce the indentation of these lines by 1 tab.

2024-09-23 03:47 UTC, omckeon commented on src/content/docs/guides/Interface/02-interface-styling.mdx
> +    SplashKit.SetInterfaceFontSize(12);
Reduce the indentation of these lines by 1 tab.

2024-09-23 03:47 UTC, omckeon commented on src/content/docs/guides/Interface/02-interface-styling.mdx
> +            while (!SplashKit.QuitRequested())
You could update this line to be `while (!window.CloseRequested)`

2024-09-25 05:12 UTC, NidhishaPahade commented
<img width="899" alt="Screenshot 2024-09-20 202852" src="https://github.com/user-attachments/assets/b1d9b086-dabb-46ba-9c79-51d891d17bb1">
<img width="973" alt="Screenshot 2024-09-20 203003" src="https://github.com/user-attachments/assets/a417f8ea-db10-4703-9785-68894f70aa23">

2024-09-26 01:23 UTC, oliverexell-bruce requested changes
In code block 1, TLS line 7: I got the following error "The name InterfaceStyle does not exist."
Fix by adding back `using SplashKitSDK;`

Otherwise looks good

2024-09-26 03:43 UTC, oliverexell-bruce approved these changes
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [X] Tested in latest Chrome
- [X] Tested in latest Firefox
- [X] npm run build
- [X] npm run preview

## Folders and Files Added/Modified

Please list the folders and files added/modified with this pull request.

- Added:
  - [X] N/A
- Modified:
  - [X] src/content/docs/guides/Interface/02-interface-styling.mdx

Looks good, great work!

2024-09-26 06:29 UTC, kay-kaushik approved these changes
The code logic is correct, concise and clear. Both the versions are consistent as well. All looks good.

2024-10-09 07:05 UTC, merged