Completion of usage examples for write_line_int
thoth-tech/splashkit.io-starlight pull request #213
Opened 2024-11-08 07:48 UTC by SimonRhook

# Overview
Added C\# OOP and Python Language versions. Updated name for top level C\# version to properly fit naming convention and fixed a number within the top level varient to properly match the output.

Splashkit Function: `write_line_int`
- [ x] Title and explanation (.txt)
- [x ] C++ code
- [x ] C# code (top-level statements)
- [x ] C# code (Object-Oriented Programming)
- [ x] Python code
- [x ] Screenshot

# Usage Example Checks
- [x ] Simple, clear demonstration of the function
- [ x] Code uses Splashkit functions
- [ x] Tested in Chrome and Firefox

2024-11-08 09:12 UTC, ShaunR1991 requested changes
Good first contribution. If you could just make the changes to the OOP version of the C# code we should be good to go.

2024-11-09 02:53 UTC, SimonRhook commented on public/usage-examples/terminal/write_line_int/write_line_int-1-simple-oop.cs
> +            WriteLine(c);
This should now be updated

2024-11-09 12:49 UTC, ShaunR1991 commented on public/usage-examples/terminal/write_line_int/write_line_int-1-simple-oop.cs
> +            WriteLine(c);
Looks good!

2024-11-10 03:45 UTC, breezy-codes commented
I've reviewed this and the code looks good, matches in correctly with how the other code was as well.
However, you will need to rebase this PR to remove the other commits Olivia has done.
There is a troubleshooting page on doing this -
https://thoth-tech.netlify.app/products/splashkit/splashkit-website/onboarding/02-troubleshooting/#how-to-rebase-your-branch

2024-11-11 03:32 UTC, closed without merging