Completion of usage examples for write_line_int
thoth-tech/splashkit.io-starlight pull request #225
Opened 2024-11-11 03:36 UTC by SimonRhook

Overview

Added C# OOP and Python Language versions. Updated name for top level C# version to properly fit naming convention and fixed a number within the top level varient to properly match the output.

Splashkit Function: write_line_int

    [ x] Title and explanation (.txt)
    [x ] C++ code
    [x ] C# code (top-level statements)
    [x ] C# code (Object-Oriented Programming)
    [ x] Python code
    [x ] Screenshot

Usage Example Checks

    [x ] Simple, clear demonstration of the function
    [ x] Code uses Splashkit functions
    [ x] Tested in Chrome and Firefox

2024-11-11 04:53 UTC, breezy-codes approved these changes
I've reviewed this pull request and the code files added are all correct and match with how the other code files were including correct commenting -

- [X] All required files are present.
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-11-11 04:56 UTC, breezy-codes commented
Prior PR with approvals:
https://github.com/thoth-tech/splashkit.io-starlight/pull/213

2024-11-12 01:59 UTC, ShaunR1991 approved these changes
See previous review from https://github.com/thoth-tech/splashkit.io-starlight/pull/213

Code looks good! Nice first contribution.
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

2024-12-02 09:51 UTC, omckeon requested changes
See comment about fixing up the python code.

2024-12-02 09:51 UTC, omckeon commented on public/usage-examples/terminal/write_line_int/write_line_int-1-simple.py
@ShaunR1991 and @breezy-codes - How was the python code run when you reviewed? This code does not run on my computer (as the function called should actually be `write_line_int` rather than `write_line`).
Unsure if this is an accident, or if Windows/Linux isn't giving the proper error?

@SimonRhook - Please update the python file to use `write_line_int` rather than `write_line`.

2024-12-02 21:53 UTC, SimonRhook commented on public/usage-examples/terminal/write_line_int/write_line_int-1-simple.py
This should be resolved now. Thinking back I published this usage example before resolving the SplashKit python install issue, so I couldn't properly test the python code. It now builds and runs error free

2024-12-03 03:20 UTC, omckeon approved these changes
Nice work. I've just moved the int type cast so that the variable is an integer.

2024-12-03 03:20 UTC, merged