Usage example/draw line on bitmap
thoth-tech/splashkit.io-starlight pull request #227
Opened 2024-11-11 08:18 UTC by NoahJCross

This usage example creates a window and draws a green line on a bitmap from a start point to an end point, with red circles marking both points.

Splashkit Function: draw_line_on_bitmap
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot
- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-11-13 23:47 UTC, breezy-codes commented
Reviewed prior PR - https://github.com/thoth-tech/splashkit.io-starlight/pull/219

2024-11-13 23:47 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line_on_bitmap/draw_line_on_bitmap-1-map-route-oop.cs
> +                // Draw the bitmap to the window
This code comment is to different than what is in the other programs. Please update this.

2024-11-13 23:48 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line_on_bitmap/draw_line_on_bitmap-1-map-route-oop.cs
> +            // Draw the route line and start and end points
Same with this line

2024-11-13 23:48 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line_on_bitmap/draw_line_on_bitmap-1-map-route-oop.cs
> +            // Fill background with white for map background
So is this comment

2024-11-13 23:49 UTC, breezy-codes requested changes
Please update the code comments in the OOP file to match how the other ones are.

2024-11-19 23:00 UTC, breezy-codes approved these changes
I've reviewed this pull request and ran all the codes in my own environment, they all ran correctly free from any errors. The code comments are consistent over all files and structure remains the same.


- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-11-28 12:50 UTC, huyhuynh2319 approved these changes
I reviewed this pull request. Everything looks to be in order, the programs work well 

- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

2024-12-16 05:32 UTC, omckeon approved these changes

2024-12-16 05:32 UTC, merged