Usage example for draw circle
thoth-tech/splashkit.io-starlight pull request #237
Opened 2024-11-12 08:27 UTC by daosgava

# Overview

A usage example has been added for the drawCircle function, implemented in C++, Python, C# (top-level code), and C# (OOP).

Splashkit Function: [Draw Circle](https://splashkit.io/api/graphics/#draw-circle-1)

# Files Included
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks
- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-11-12 23:06 UTC, breezy-codes commented on public/usage-examples/graphics/draw_circle_record/draw_circle_record-1-simple-oop.cs
> +}
C# OOP code cannot use - `using static SplashKitSDK.SplashKit;`

Please refer to the documentation site on how to do C# OOP program codes and then fix this program.
https://thoth-tech.netlify.app/products/splashkit/splashkit-website/tutorials-documentation/04-oop-styling/

2024-11-12 23:16 UTC, breezy-codes commented on public/usage-examples/graphics/draw_circle_record/draw_circle_record-1-simple-oop.cs
> +            // Draw the circles with different colors
This comment is different over all 4 files, please update so its the exact same comment on all.

2024-11-12 23:17 UTC, breezy-codes commented on public/usage-examples/graphics/draw_circle_record/draw_circle_record-1-simple.cpp
> +    // Define the center of the circles
This comment line is different, in both C# files you do -
`// Define the center point for all circles`

But in python and cpp this is a different comment. Please update to ensure the comment is the same over all 4 files.

2024-11-12 23:18 UTC, breezy-codes commented on public/usage-examples/graphics/draw_circle_record/draw_circle_record-1-simple.cpp
> +    // Create 4 circles with different radii
Same issue with this comment.

2024-11-12 23:19 UTC, breezy-codes requested changes
I've left comments on some sections of your code on minor fixes and changes. 

Please update the description of this pull request to match the required one for usage examples specified here - 
https://thoth-tech.netlify.app/products/splashkit/splashkit-website/usage-examples/03-usage-pull-request/

Then make the requested changes.

2024-11-13 23:41 UTC, breezy-codes approved these changes
All requested changes have been made, code runs correctly and meets the standards of how usage examples should be for the site.
I approve this PR

- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-11-28 12:47 UTC, huyhuynh2319 approved these changes
I've reviewed the usage examples. Everything ran without issue.

### **Checks**

- [x]  All required files are present.
- [x]  Title and explanation (.txt)
- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code

### **Tests done**

- [x]  C++ code ran correctly.
- [x]  C# top level code ran correctly.
- [x]  C# OOP code ran correctly.
- [x]  Python code ran correctly.

2024-12-16 06:20 UTC, omckeon approved these changes
I've made some changes to the code, just to make this clearer, and to ensure no OO code in the top level C# code.

2024-12-16 06:20 UTC, merged