Added usage example for fill_quad
thoth-tech/splashkit.io-starlight pull request #240
Opened 2024-11-13 04:54 UTC by SimonRhook

# Overview

Added new usage example for fill_quad including C\# OOP and Top level, C++ and Python

# Files Included

Splashkit Function: `fill_quad`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-11-17 04:36 UTC, NoahJCross approved these changes
# Peer Review
I've reviewed the fill_quad usage example which draws a diamond with 4 quads. The code runs with no errors.

# Checks
- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.

# Tests done
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

2024-11-20 22:07 UTC, breezy-codes commented on public/usage-examples/graphics/fill_quad/fill_quad-1-simple-oop.cs
> +namespace WriteLineInt
The namespace needs to be updated.

2024-11-20 22:08 UTC, breezy-codes requested changes
I've reviewed this PR, all code works correctly. Just one small change requested before I can approve this PR.

2024-11-20 22:40 UTC, breezy-codes approved these changes
I've reviewed this pr, all code runs correctly and is free of errors. Code comments and structure remain consistent over all files.

I approve this PR

- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-12-02 10:40 UTC, omckeon commented
See my review comments on the "Create usage example for draw_line_on_window" PR [here](https://github.com/thoth-tech/splashkit.io-starlight/pull/235#pullrequestreview-2472288685) and make relevant updates.

2024-12-16 07:11 UTC, omckeon approved these changes

2024-12-16 07:12 UTC, merged