Added usage examples for the draw_line function
thoth-tech/splashkit.io-starlight pull request #246
Opened 2024-11-14 04:33 UTC by SimonRhook

# Overview

Added usage examples for the draw_line function including C\# OOP and Top Level, C++ and python 

# Files Included

Splashkit Function: `function_name`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-11-21 05:14 UTC, Jinx-means-jinx reviewed
Check the code for oop and running with no error
![image](https://github.com/user-attachments/assets/8387c8c0-d355-4c1d-99ab-4d1f72a0c1b3)

Check the code for top level and running with no error
![image](https://github.com/user-attachments/assets/28ac81c5-c23e-4006-940f-dc4af8db167a)

Check the code for C++ and running with no error
![image](https://github.com/user-attachments/assets/1729cf74-e9a1-4181-b640-d3cc83f46cfd)

Check the code for python and running with no error
![image](https://github.com/user-attachments/assets/0eceacdf-df46-4531-8c75-d6ff9ab0f2e9)

2024-11-21 05:15 UTC, Jinx-means-jinx commented
Great work!

2024-11-25 04:23 UTC, breezy-codes requested changes
I've reviewed this PR, all code runs well and free of errors.
I just have a few formatting requests, it also might be good to be a smidge more descriptive in the txt file, like what DO the lines form?

2024-11-25 04:23 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line/draw_line-1-simple-oop.cs
> +
remove this line

2024-11-25 04:23 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line/draw_line-1-simple-top-level.cs
> +
and this one

2024-11-25 04:23 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line/draw_line-1-simple-top-level.cs
> +
and this one

2024-11-25 04:23 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line/draw_line-1-simple.cpp
> +
and this one

2024-11-25 04:23 UTC, breezy-codes commented on public/usage-examples/graphics/draw_line/draw_line-1-simple.py
> +
and this one too

2024-11-25 05:32 UTC, breezy-codes approved these changes
I've reviewed this PR, all code files run correctly and are free of any errors. Code comments are consistent and so is the code.

I approve of this PR.


- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-12-16 07:54 UTC, omckeon approved these changes

2024-12-16 07:54 UTC, merged