Added usage example for random_window_point
thoth-tech/splashkit.io-starlight pull request #264
Opened 2024-11-19 02:38 UTC by SimonRhook

# Overview

This usage example demonstrates the ussage of the random_window_point function to randomly place sprites on a window

# Files Included

Splashkit Function: `function_name`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-12-07 02:07 UTC, breezy-codes requested changes
I've left a few requests for changes on this PR

2024-12-07 02:07 UTC, breezy-codes commented on public/usage-examples/geometry/random_window_point/random_window_point-1-simple-top-level.cs
> +CloseAllWindows();
This line should be `CloseWindow(Window);`

2024-12-07 02:07 UTC, breezy-codes commented on public/usage-examples/geometry/random_window_point/random_window_point-1-simple.py
> +close_all_windows()
Similarly here, as you only open one window, you only need to call `close_window(window)`

2024-12-07 02:07 UTC, breezy-codes commented on public/usage-examples/geometry/random_window_point/random_window_point-1-simple.cpp
> +    close_all_windows();
Similarly here, as you only open one window, you only need to call `close_window(window);`

2024-12-07 02:07 UTC, breezy-codes commented on public/usage-examples/geometry/random_window_point/random_window_point-1-simple.txt
> +The following code shows examples of using [Random Window Point](/api/geometry#random-window-point) to select a random point to draw the portal sprites.
Change to say " shows an example of"
instead of "examples"

2024-12-07 06:44 UTC, breezy-codes approved these changes
I've reviewed this PR, all code files run correctly and are free of any errors. Code comments are consistent and so is the code.

I approve of this PR.


- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-12-11 11:50 UTC, huyhuynh2319 approved these changes
I've reviewed the usage examples. Everything ran without issue.

### **Checks**

- [x]  All required files are present.
- [x]  Title and explanation (.txt)
- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code

### **Tests done**

- [x]  C++ code ran correctly.
- [x]  C# top level code ran correctly.
- [x]  C# OOP code ran correctly.
- [x]  Python code ran correctly.

2025-01-31 07:39 UTC, merged