Added usage example for random_bitmap_point
thoth-tech/splashkit.io-starlight pull request #265
Opened 2024-11-19 03:22 UTC by SimonRhook

# Overview
Demonstrates usage for random_bitmap_point, used to draw a random quad onto a window

# Files Included

Splashkit Function: `random_bitmap_point`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-11-23 06:30 UTC, EthanRin approved these changes
I've reviewed this usage example and have tested each implementation of the program across different languages.
The code is well-structured and is consistent throughout each implementations. I approved of this PR.

### Checklist
- [x] Code uses SplashKit function 
- [x] Code demonstrates uses of the function 
- [x] Python code ran as expected.
- [x] C# OOP code ran as expected.
- [x] C# Top Level code ran as expected
- [x] C++ Code ran as expected 

### Files required 
- [x] Python code 
- [x] C# OOP code
- [x] C# Top Level code 
- [x] C++ Code 
- [x] Screenshot of the program running 
- [x] Title and description

2024-11-25 04:19 UTC, breezy-codes requested changes
I've reviewed this PR, the concept is quite cool, all programs run well, but I have a few formatting requests.
Once fixed I'll approve this PR.

2024-11-25 04:19 UTC, breezy-codes commented on public/usage-examples/geometry/random_bitmap_point/random_bitmap_point-1-simple-top-level.cs
> +
Unnecessary extra line here, please remove.

2024-11-25 04:19 UTC, breezy-codes commented on public/usage-examples/geometry/random_bitmap_point/random_bitmap_point-1-simple.cpp
> +
Unnecessary extra line here, please remove.

2024-11-25 04:19 UTC, breezy-codes commented on public/usage-examples/geometry/random_bitmap_point/random_bitmap_point-1-simple-oop.cs
> +                SplashKit.RandomBitmapPoint(bmp),SplashKit.RandomBitmapPoint(bmp),
make the second one in here be on a new line, this part - `SplashKit.RandomBitmapPoint(bmp)`

2024-11-25 05:30 UTC, breezy-codes approved these changes
I've reviewed this PR, all code files run correctly and are free of any errors. Code comments are consistent and so is the code.

I approve of this PR.


- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2025-01-20 08:50 UTC, merged