Added usage example for same_point
thoth-tech/splashkit.io-starlight pull request #269
Opened 2024-11-20 03:02 UTC by SimonRhook

# Overview

Adds usage example for same_point displayed by a simple guessing game

# Files Included

Splashkit Function: `same_point`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-11-24 05:03 UTC, breezy-codes requested changes
While this is cool, I think this could be improved by adding a little "getting warmer" or "getting colder".
Otherwise its kind of a stab in the dark hoping you might get right or wrong.

I have run the programs and the all run well, and are free of errors.

2024-11-24 06:52 UTC, SimonRhook commented
I have added a a clue system which simply states higher lower or correct for each coord x and y to make the guessing a bit more intuitive

2024-11-24 22:14 UTC, breezy-codes approved these changes
I really like the addition of the clues, it helps in guessing the right values and makes this usage example quite cool.
The code runs correctly and free of any errors, the structures remain the same over all versions.

I approve of this PR.


- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-11-28 12:45 UTC, huyhuynh2319 approved these changes
I've reviewed the usage examples. Everything ran without issue.

### **Checks**

- [x]  All required files are present.
- [x]  Title and explanation (.txt)
- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code

### **Tests done**

- [x]  C++ code ran correctly.
- [x]  C# top level code ran correctly.
- [x]  C# OOP code ran correctly.
- [x]  Python code ran correctly.

2024-12-02 10:46 UTC, omckeon commented
See my review comments on the "Create usage example for draw_line_on_window" PR [here](https://github.com/thoth-tech/splashkit.io-starlight/pull/235#pullrequestreview-2472288685) and make relevant updates.

And please remove any use of `while(true)` - this is not good practice.

2025-01-20 12:36 UTC, omckeon reviewed
I've updated the code a bit, as I realised this would be useful to show validating something like a point_2d type (for intro students).

2025-01-20 12:37 UTC, merged