Draw ellipse
thoth-tech/splashkit.io-starlight pull request #271
Opened 2024-11-20 12:20 UTC by Jinx-means-jinx

# Overview
Add new usage example "Draw ellipse".

![image](https://github.com/user-attachments/assets/845a5f93-0fa6-45b2-b705-278a4ec35161)
![image](https://github.com/user-attachments/assets/1cc3afa8-0637-440e-88e4-a84f505e7fae)

# Files Included
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks
- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-12-12 04:23 UTC, huyhuynh2319 requested changes

2024-12-12 04:23 UTC, huyhuynh2319 commented on public/usage-examples/graphics/draw_ellipse/draw_ellipse-1-radiating-wave.py
> +    random_color = rgb_color(
It would become rnd_int(255), rnd_int(255), rnd_int(255)

2024-12-14 21:37 UTC, ShaunR1991 approved these changes
All code works well and the output is exciting. Happy to approve, however would recommend that you add some comments into your code to explain the key components and what someone who might pick up this usage example might change to influence the output.

2025-01-04 05:09 UTC, Jinx-means-jinx commented
Commit added

2025-01-20 10:45 UTC, merged