Added usage example for point_in_rectangle
thoth-tech/splashkit.io-starlight pull request #273
Opened 2024-11-21 04:21 UTC by SimonRhook

# Overview

Adds usage example showing point in rectangle. program has a little rectangle "jail" that sends the police after the mouse cursor if it escapes 

# Files Included

Splashkit Function: `point_in_rectangle`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-11-25 02:38 UTC, rmachu commented on public/usage-examples/geometry/point_in_rectangle/point_in_rectangle-1-jailbreak.txt
Please fix up the link here. ('point-in0rectangle')

2024-11-27 03:47 UTC, rmachu requested changes
Hi Simon, apologies for the delayed response. I have reviewed this pull request and suggest some changes.  

-  I suggest making the second while loop into an if statement instead as it is more appropriate for the logic here, a while loop could cause it to ignore the other events. If you do this, you can also remove the _ProcessEvents_ and _If QuitRequested_ at the end of your second loop, since you won't have to break an if statement. 

- You can remove the _mouse_point = SplashKit.MousePosition();_  in the second loop as you've already initialised it in the main one.

- I suggest moving the _process_events_ to the very start of the main _QuitRequested_ loop because you want the program to start processing events from the beginning. 

- Also adding a _CloseAllWindows_ function at the end would be great for good resource management. 

Hope this makes sense!

2024-12-02 10:47 UTC, omckeon commented
See my review comments on the "Create usage example for draw_line_on_window" PR [here](https://github.com/thoth-tech/splashkit.io-starlight/pull/235#pullrequestreview-2472288685) and make relevant updates.

And check the line spacing is consistent and makes sense. (No double empty lines etc)

2024-12-03 01:13 UTC, SimonRhook commented
> See my review comments on the "Create usage example for draw_line_on_window" PR [here](https://github.com/thoth-tech/splashkit.io-starlight/pull/235#pullrequestreview-2472288685) and make relevant updates.
> 
> And check the line spacing is consistent and makes sense. (No double empty lines etc)

In this example I have left lines 30 and 33 as SplashKit.RefreshScreen(2); rather than Window.Refresh(2); as the latter was not working as intended and had no affect on target FPS

2024-12-11 11:48 UTC, huyhuynh2319 requested changes
You should change the base "thoth-tech: main" to the "thoth-tech: usage-example"

2024-12-12 00:11 UTC, SimonRhook commented
@huyhuynh2319 Good catch, I've fixed this now

2024-12-15 04:45 UTC, huyhuynh2319 approved these changes
I've reviewed the usage examples. Everything ran without issue.

### **Checks**

- [x]  All required files are present.
- [x]  Title and explanation (.txt)
- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code

### **Tests done**

- [x]  C++ code ran correctly.
- [x]  C# top level code ran correctly.
- [x]  C# OOP code ran correctly.
- [x]  Python code ran correctly.

2025-02-17 09:22 UTC, merged