Usage examples 1 - Kartik Kaushik
thoth-tech/splashkit.io-starlight pull request #28
Opened 2024-05-17 13:33 UTC by kay-kaushik

# Description 

This pull request features usage exaples for create_sprite(), draw_sprite(), move_sprite(), free_sprite() and key_typed() functions. They are really detailed examples with descriptive gifs and images. The usage examples are in cpp language.

# changes

I have created 3 files per function including txt, png and cpp files.

#  testing 

I tested all the changes made to the code on my machine before creating the pull request.

#  benefits

These high quality usage examples give more context to the functions. This will help users reading the documentation to better understand the function. This will result in faster development.

2024-05-17 13:34 UTC, kay-kaushik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Code Usage Examples for:](https://trello.com/c/AaJdb3Pr/596-create-code-usage-examples-for)

2024-05-18 00:53 UTC, hugglesfox requested changes
Looks good, just a couple of questions and spelling mistakes. 

However it looks like you've created your usage-examples branch from the branch which you fixed the dead links on, meaning that those commits have been included in the PR. It would be nice to remove the commits fixing the dead links from this PR (hint: use `git rebase -i`).

2024-05-18 00:53 UTC, hugglesfox commented on src/assets/usage-examples-code/input/key_typed/key_typed-1-type-key.cpp
> +    // widow to draw the sprite on
```suggestion
    // window to draw the sprite on
```

2024-05-18 00:53 UTC, hugglesfox commented on src/assets/usage-examples-code/input/key_typed/key_typed-1-type-key.cpp
> +    // setting the co-ordinates in refrence to the window
Isn't this centering the sprite on the window, rather then setting it's coordinates relative to?

2024-05-18 00:53 UTC, hugglesfox commented on src/assets/usage-examples-code/input/key_typed/key_typed-1-type-key.txt
> +### key_typed() usage exaple
```suggestion
### key_typed() usage example
```

This mistake has been made in the other example descriptions too

2024-05-18 00:53 UTC, hugglesfox commented on src/assets/usage-examples-code/input/key_typed/key_typed-1-type-key.txt
Should this be an mdx file rather then a txt?

2024-05-18 00:53 UTC, hugglesfox commented on src/assets/usage-examples-code/input/key_typed/key_typed-1-type-key.txt
> +The following code is an example of using [key typed](https://splashkit.io/api/input/#key-typed) to move a sprite in a game window to the right after right key is typed.
```suggestion
The following code is an example of using [`key_typed`](https://splashkit.io/api/input/#key-typed) to move a sprite in a game window to the right after right key is typed.
```

Should probably run this past @omckeon, however my preference would be to have the function name in snake_case like how it is in the code and to wrap it in a code block. Same could be done for the page title.

2024-05-18 00:53 UTC, hugglesfox commented on src/assets/usage-examples-code/sprites/draw_sprite/draw_sprite-1-drawing-sprite.cpp
> +    //drawing the sprite
```suggestion
    // drawing the sprite
```

2024-05-19 02:26 UTC, lexlam1524 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Naming refactor of ExecutionEnvironment and related code](https://trello.com/c/mqHADqTC/584-naming-refactor-of-executionenvironment-and-related-code)

2024-05-19 04:49 UTC, omckeon commented on src/assets/usage-examples-code/input/key_typed/key_typed-1-type-key.txt
I've requested these files to be .txt for now. They would then be used in a script to generate the .mdx files.

2024-06-25 10:39 UTC, omckeon commented
Just closing PRs that can't/won't be merged (due to formatting or other issues), this is separate from any capstone grading.

2024-06-25 10:39 UTC, closed without merging