Added two usage examples for point on line
thoth-tech/splashkit.io-starlight pull request #280
Opened 2024-11-23 03:55 UTC by SimonRhook

# Overview

Added usage examples for point on line, there is a simple use case and a more complex version that shows a volume slider type example.
# Files Included

Splashkit Function: `point_on_line`
- [x] Title and explanation (.txt)
- [x] C++ code
- [x] C# code (top-level statements)
- [x] C# code (Object-Oriented Programming)
- [x] Python code
- [x] Screenshot

# Usage Example Checks

- [x] Simple, clear demonstration of the function
- [x] Code uses Splashkit functions
- [x] Tested in Chrome and Firefox

2024-12-02 10:49 UTC, omckeon commented
See my review comments on the "Create usage example for draw_line_on_window" PR [here](https://github.com/thoth-tech/splashkit.io-starlight/pull/235#pullrequestreview-2472288685) and make relevant updates.

2024-12-07 02:14 UTC, breezy-codes requested changes
Overall, these programs are great and show the specific functions well.
But I've left requests for some changes to the code files.

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-1-simple-top-level.cs
> +CloseAllWindows();
This line should be `CloseWindow(Window);`

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-2-volume-slide-top-level.cs
> +CloseAllWindows();
This line should be `CloseWindow(Window);`

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-1-simple.cpp
> +    close_all_windows();
Similarly here, as you only open one window, you only need to call `close_window(window);`

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-2-volume-slide.cpp
> +    close_all_windows();
Similarly here, as you only open one window, you only need to call `close_window(window);`

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-2-volume-slide.py
> +close_all_windows()
Similarly here, as you only open one window, you only need to call `close_window(window)`

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-1-simple.py
> +close_all_windows()
Similarly here, as you only open one window, you only need to call `close_window(window)`

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-1-simple.py
> +        # Draw text if cursor is on line
put this comment above the if, like how it was done in other code files.

2024-12-07 02:14 UTC, breezy-codes commented on public/usage-examples/geometry/point_on_line/point_on_line-2-volume-slide.cpp
> +    std::string volume = "Volume: ";
Because you've done `#include <string>`, you don't need `std::` here

2024-12-07 06:43 UTC, breezy-codes approved these changes
I've reviewed this PR, all code files run correctly and are free of any errors. Code comments are consistent and so is the code.

I approve of this PR.


- [X] All required files are present.
  - [X] Title and explanation (.txt)
  - [X] C++ code
  - [X] C# code (top-level statements)
  - [X] C# code (Object-Oriented Programming)
  - [X] Python code
- [X] Code correctly uses Splashkit functions.
- [X] Code clearly demonstrates the function.
- [X] All versions maintain the same structure and comments.
- [X] C++ code ran correctly.
- [X] C# top level code ran correctly.
- [X] C# OOP code ran correctly.
- [X] Python code ran correctly.

2024-12-11 09:38 UTC, EthanRin requested changes
The implementation of the point on line usage examples looks great and I personally like the Volume slide, a fun addition of how the function can be used! 

Although, I did notice for the C# Top-Level and CPP implementation for both examples, I ran into an error with the `close_window` function where it was saying `Window` (C#) or `window` (CPP) was a type. Is it possible to update this by declaring a Window variable when calling the `open_window` and passing that variable in `close_window`.

2024-12-12 05:00 UTC, EthanRin approved these changes
I've reviewed this usage example and have tested each implementation of the program across different languages.
The code is well-structured and is consistent throughout each implementations. I approved of this PR.

### Checklist
- [x] Code uses SplashKit function 
- [x] Code demonstrates uses of the function  
- [x] Python code ran as expected.
- [x] C# OOP code ran as expected.
- [x] C# Top Level code ran as expected
- [x] C++ Code ran as expected 

### Files required 
- [x] Python code 
- [x] C# OOP code
- [x] C# Top Level code 
- [x] C++ Code 
- [x] Screenshot of the program running 
- [x] Title and description

2025-01-30 15:12 UTC, merged