Sprite collisions usage
thoth-tech/splashkit.io-starlight pull request #284
Opened 2024-11-23 10:46 UTC by ShaunR1991

# Description

This pull request adds simple usage examples for the following sprite collision physics functions in SplashKit:

- `sprite_bitmap_collision`
- `sprite_bitmap_collision_with_cell`
- `sprite_bitmap_collision_with_cell_at_point`
- `sprite_collision`
- `sprite_point_collision`
- `sprite_rectangle_collision`

The purpose of this update is to help users understand the functionality of these sprite collision physics functions in SplashKit by providing detailed examples across supported languages (C++, C#, and Python).

Each example includes:
- C++ Code
- C# Code (Top-Level and Object-Oriented versions)
- Python Code
- Text Description File
- Image of Output
- Resource zip file

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (update or new)

## How Has This Been Tested?

All functions were run and tested to ensure output was as expected.

## Testing Checklist

- [x] Tested in latest Chrome
- [x] Tested in latest Firefox
- [x] `npm run build`
- [x] `npm run preview`

## Checklist

### If involving code

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### If modified config files

- [ ] I have checked the following files for changes:
  - [ ] package.json
  - [ ] astro.config.mjs
  - [ ] netlify.toml
  - [ ] docker-compose.yml
  - [ ] custom.css

## Additional Notes

Each example is designed to demonstrate only the basic functionality of sprite collision physics functions in SplashKit. The resources provided will enable users to replicate, modify, and understand how to implement the functions and what the expected outputs might look like.

2024-11-28 00:23 UTC, ctrlvish requested changes
I've reviewed the following functions
`sprite_bitmap_collision`
`sprite_bitmap_collision_with_cell`
`sprite_bitmap_collision_with_cell_at_point`
`sprite_collision`
`sprite_point_collision`
`sprite_rectangle_collision`
- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [ ] C# OOP code ran correctly.
- [x] Python code ran correctly.

feedback: sprite_rectangle_collision-simple-oop.cs, line 32 and 34 the function is missing the SplashKit. prefix causing it to not run.

2024-11-28 04:51 UTC, rmachu requested changes
Hi Shaun, I've reviewed this pull request and request a few changes. Other than this everything else looks good.

2024-11-28 04:51 UTC, rmachu commented on public/usage-examples/physics/sprite_bitmap_collision/sprite_bitmap_collision-simple-oop.cs
> +            SplashKit.ClearScreen(SplashKit.ColorWhite());
Color in the OOP files can just be _Color.White_ instead.

2024-11-28 04:51 UTC, rmachu commented on public/usage-examples/physics/sprite_rectangle_collision/sprite_rectangle_collision-simple.cpp
> +    // Define the first rectangle
Inconsistent comments, this isn't in the other programs.

2024-11-28 04:51 UTC, rmachu commented on public/usage-examples/physics/sprite_rectangle_collision/sprite_rectangle_collision-simple-oop.cs
> +            if (SpriteRectangleCollision(skSprite, testRectangle1))
Error in the method syntax here for OOP.

2024-12-01 00:37 UTC, ShaunR1991 commented
> Hi Shaun, I've reviewed this pull request and request a few changes. Other than this everything else looks good.

Thanks for the thorough review and good spots with the errors. Fixes have been pushed.

2024-12-15 09:38 UTC, rmachu approved these changes
I've reviewed this Sprite Collisions PR and after the changes made, I approve the PR. Sorry for the delayed follow-up.

# Checks
- [x] All required files are present.
  - [ ] Title and explanation (.txt)
  - [ ] C++ code
  - [ ] C# code (top-level statements)
  - [ ] C# code (Object-Oriented Programming)
  - [ ] Python code
- [ ] Code correctly uses Splashkit functions.
- [ ] Code clearly demonstrates the function.
- [ ] All versions maintain the same structure and comments.

# Tests done
- [ ] C++ code ran correctly.
- [ ] C# top level code ran correctly.
- [ ] C# OOP code ran correctly.
- [ ] Python code ran correctly.

2025-02-02 16:57 UTC, omckeon approved these changes
Had to remove the examples using the "cell" parameters due to the "cell" part not being shown in a useful way

2025-02-02 16:57 UTC, merged