Terminal Usage Example Creation Part 2
thoth-tech/splashkit.io-starlight pull request #290
Opened 2024-11-24 02:01 UTC by breezy-codes

This PR contains part 2 of filling out the missing usage examples for terminal.
This PR contains `write_line_double`, `read_char`, `read_line`, and `terminal_has_input`.

- [X] Title and explanation (.txt)
- [X] C++ code
- [X] C# code (top-level statements)
- [X] C# code (Object-Oriented Programming)
- [X] Python code
- [X] Screenshot
- [X] Simple, clear demonstration of the function
- [X] Code uses Splashkit functions
- [X] Tested in Chrome and Firefox

![write_line_double-1-sums](https://github.com/user-attachments/assets/66c77427-3728-433a-b927-03c718b3ae5b)
![read_char-1-ASCII-checker](https://github.com/user-attachments/assets/00538080-5129-4706-8e08-241e5b7b6520)
![read_line-1-user-info](https://github.com/user-attachments/assets/f59ef74f-d078-4ff1-9fd7-ebe6dcdc603d)
![terminal_has_input-1-echo-words](https://github.com/user-attachments/assets/5494a0e0-763b-4022-8cb0-634dfeacf9eb)

2024-12-11 02:49 UTC, SimonRhook requested changes
I've left some comments for change. Mainly removing while(true) and updates the same as PR #289. 

The programs do a great job of demonstrating there respective functions  and the code runs error free. Once the changes are made I will approve this PR

2024-12-11 02:49 UTC, SimonRhook commented on public/usage-examples/terminal/read_char/read_char-1-ASCII-checker-oop.cs
> +namespace Program
See PR #289

2024-12-11 02:49 UTC, SimonRhook commented on public/usage-examples/terminal/read_char/read_char-1-ASCII-checker-oop.cs
> +            while (true)
Remove while(true) [per this comment](https://github.com/thoth-tech/splashkit.io-starlight/pull/269#issuecomment-2511186618)

2024-12-11 02:49 UTC, SimonRhook commented on public/usage-examples/terminal/read_char/read_char-1-ASCII-checker.txt
> +### Check ASCII Values
See PR #289

2024-12-11 02:49 UTC, SimonRhook commented on public/usage-examples/terminal/terminal_has_input/terminal_has_input-1-echo-words-oop.cs
> +            while (true)
See above

2024-12-11 02:49 UTC, SimonRhook commented on public/usage-examples/terminal/read_line/read_line-1-user-info.txt
> +The following code shows an example of using [delay](/api/terminal/#read-line), where the program asks the user 3 questions and reads the response for each question. The program then prints the user'
Fix the link text here

2024-12-11 02:49 UTC, SimonRhook commented on public/usage-examples/terminal/write_line_double/write_line_double-1-sums-oop.cs
> +            // Output the results using SplashKit.WriteLine(double data)
I don't think its necessary to have the namespace in the comment

2024-12-15 08:40 UTC, SimonRhook approved these changes
After the requested changes were made I can now approve this PR.
The usage examples do a good job of demonstrating the functions and the code runs error free 
- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

2024-12-15 09:57 UTC, ctrlvish requested changes

2024-12-15 09:57 UTC, ctrlvish commented on public/usage-examples/terminal/read_char/read_char-1-ASCII-checker.txt
Hi @breezy-codes, I've reviewwed this PR and would like to request one change to the naming convention to API hyperlinks in the .txt files

2025-04-26 05:00 UTC, closed without merging