Usage Example - Free Font
thoth-tech/splashkit.io-starlight pull request #297
Opened 2024-11-25 01:34 UTC by rmachu

# Overview
This example uses free_font to free a loaded font to load in a new one. The fonts are displayed as text on a window.

Splashkit Function: `Free_Font`

# Files Included
- [ ] Title and explanation (.txt)
- [ ] C++ code
- [ ] C# code (top-level statements)
- [ ] C# code (Object-Oriented Programming)
- [ ] Python code
- [ ] Screenshot

# Usage Example Checks
- [ ] Simple, clear demonstration of the function
- [ ] Code uses Splashkit functions
- [ ] Tested in Chrome and Firefox

2024-11-27 06:05 UTC, SimonRhook requested changes
Nice work on this usage example, I think it does a good job on displaying how to properly use free_font. Everything runs well and error free.

I have left some comments with a few minor corrections that need to be addressed and once they are fixed I can approve this PR

2024-11-27 06:05 UTC, SimonRhook commented on public/usage-examples/graphics/free_font/free_font-1-simple-top-level.cs
> +// Open a new window
This comment is slightly different from other variants

2024-11-27 06:05 UTC, SimonRhook commented on public/usage-examples/graphics/free_font/free_font-1-simple-top-level.cs
> +SplashKitSDK.Window wnd = OpenWindow("Font Styles", 600, 500);
There is no need to qualify the namespace here in Top level

2024-11-27 06:05 UTC, SimonRhook commented on public/usage-examples/graphics/free_font/free_font-1-simple.py
Comments in this file are a bit mixed up compared to others.

2024-11-27 06:05 UTC, SimonRhook commented on public/usage-examples/graphics/free_font/free_font-1-simple.cpp
> +
I know its not strictly necessary, but its a good practice to end your file with return 0; in c++

2024-12-09 06:59 UTC, Jinx-means-jinx reviewed
good work!
# Peer Review

I've reviewed the ...

# Checks
- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [ ] C# code (Object-Oriented Programming)
  - [ ] Python code
- [ ] Code correctly uses Splashkit functions.
- [ ] Code clearly demonstrates the function.
- [ ] All versions maintain the same structure and comments.

# Tests done
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

2025-02-17 06:46 UTC, omckeon reviewed
I've updated the example to properly highlight the use of freeing the font

2025-02-17 06:46 UTC, merged