sprite_set_velocity
thoth-tech/splashkit.io-starlight pull request #307
Opened 2024-11-27 00:04 UTC by huyhuynh2319

Describe the example and what it demonstrates.
The code demonstrates the use of sprite_set_velocity

Splashkit Function: sprite_set_velocity

Files Included

- [x]  C# code (Object-Oriented Programming)
- [x]  python code

Usage Example Checks

- [x]  Simple, clear demonstration of the function
- [x]  Code uses Splashkit functions
- [x]  Tested in Chrome and Firefox

2024-12-11 00:34 UTC, SimonRhook requested changes
I've left some comments requesting some simple changes. Once these are made I can approve this PR

2024-12-11 00:34 UTC, SimonRhook commented on public/usage-examples/sprites/sprite_set_velocity/sprite_set_velocity-1-simple-oop.cs
> +            // Open a new window
The comment here and on line 12, 21, and 35 do not exits in the other files. Either remove them from here or add them into existing files.

2024-12-11 00:34 UTC, SimonRhook commented on public/usage-examples/sprites/sprite_set_velocity/sprite_set_velocity-1-simple.py
> +    # Create vector for sprite's velocity
Fix indentation here

2024-12-11 00:34 UTC, SimonRhook commented on public/usage-examples/sprites/sprite_set_velocity/sprite_set_velocity-1-simple.py
> +        process_events()
Fix code indentation in the while loop

2024-12-11 00:34 UTC, SimonRhook commented on public/usage-examples/sprites/sprite_set_velocity/sprite_set_velocity-1-simple-oop.cs
This could portray OO a bit better by setting the sprite variables like playerSprite.X = 300 and playerSprite.Velocity etc.

2024-12-11 00:34 UTC, SimonRhook commented on public/usage-examples/sprites/sprite_set_velocity/sprite_set_velocity-1-simple-oop.cs
> +namespace velocity
Make this name space a bit more descriptive, such as SpriteSetVelocityExample

2025-02-10 12:07 UTC, omckeon commented
Changes not fixed

2025-02-10 12:07 UTC, closed without merging