Point point angle
thoth-tech/splashkit.io-starlight pull request #309
Opened 2024-11-27 03:39 UTC by Jinx-means-jinx

# Overview
Add usage example point point angle to calculate angle between original point and mouse.

Splashkit Function: `point_point_angle`
![image](https://github.com/user-attachments/assets/e7eeea2b-25f8-4553-a139-ce82bd139736)
![image](https://github.com/user-attachments/assets/ec4dfb60-84cd-4b20-a054-b628551d8b5a)
![image](https://github.com/user-attachments/assets/4a001586-2852-4dc1-bd40-c615c28f0371)

# Files Included
- [ ] Title and explanation (.txt)
- [ ] C++ code
- [ ] C# code (top-level statements)
- [ ] C# code (Object-Oriented Programming)
- [ ] Python code
- [ ] Screenshot

# Usage Example Checks
- [ ] Simple, clear demonstration of the function
- [ ] Code uses Splashkit functions
- [ ] Tested in Chrome and Firefox

2024-11-27 05:31 UTC, SimonRhook requested changes
This program runs error free and does a good job of displaying the point_point_angle function however I am requesting some changes.

Currently the code comments are inconsistent across all files, can you please go back and ensure they are matching? 
Also the code formatting is quite different across files with a few extra added spaces here and there.

I have also left 2 comments on the code to be fixed which are very minor changes.

Once you make these changes I can approve this PR

2024-11-27 05:31 UTC, SimonRhook commented on public/usage-examples/geometry/point_point_angle/point_point_angle-1-simple.cpp
> +    open_window("Point point angle", 800, 600);
2nd point in window title isn't capitalized as it is in other files

2024-11-27 05:32 UTC, SimonRhook commented on public/usage-examples/geometry/point_point_angle/point_point_angle-1-simple-top-level.cs
> +while (!SplashKit.QuitRequested())
no need for the SplashKit. namespace call in top level

2024-12-12 04:56 UTC, SimonRhook requested changes
Looks like you missed updating the code comments. Everything else looks good so once you update them I'm happy to approve

2024-12-12 04:56 UTC, SimonRhook commented on public/usage-examples/geometry/point_point_angle/point_point_angle-1-simple.cpp
The code comments are different in this file still. Please update them to match your C# comments

2024-12-12 04:56 UTC, SimonRhook commented on public/usage-examples/geometry/point_point_angle/point_point_angle-1-simple.py
The code comments are different in this file still. Please update them to match your C# comments

2024-12-14 21:52 UTC, ShaunR1991 reviewed
Functionally this code does what it says on the tin, however a few points for clarity and consistency. 

Would recommend having the comments consistent across the different languages. 
Would also recommend perhaps having the angle output on the window with a line drawn between the mouse and the point on the screen. 
It feels unintuitive to look for a point on the screen where the mouse is and then looking at the console for the output. It will also stop the console from being flooded with messages. Useful information may be overwritten nearly as quickly as it is presented.

2024-12-14 21:56 UTC, ShaunR1991 approved these changes
Code executes as expected and is commented well. Nothing new to add, solid usage example.

2025-01-04 05:43 UTC, Jinx-means-jinx commented
Fixed Thanks!

2025-01-30 02:45 UTC, closed without merging

2025-01-30 02:45 UTC, omckeon commented
This example was not quite clear enough, so won't be used on the live site. Good try though.