fill triangle on window
thoth-tech/splashkit.io-starlight pull request #314
Opened 2024-11-27 05:31 UTC by huyhuynh2319

Splashkit Function: fill_triangle_on_window

- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code
- [x]  Screenshot
- [x]  Title and explanation (.txt)

Usage Example Checks

- [x]  Simple, clear demonstration of the function
- [x]  Code uses Splashkit functions
- [x]  Tested in Chrome and Firefox

2024-11-28 21:24 UTC, EthanRin requested changes
It seems that each implementation is using the function "fill_triangle" rather than "fill_triangle_on_window". I've attached the function documentation page below. Please change the examples to use the function you're trying to showcase. 

https://splashkit.io/api/graphics/#fill-triangle-on-window

2024-12-09 03:27 UTC, omckeon commented
@huyhuynh2319 Please update the PR description to use the proper [pull_request_template](https://github.com/thoth-tech/splashkit.io-starlight/blob/main/.github/pull_request_template.md).

2024-12-09 07:34 UTC, huyhuynh2319 commented
Sorry about the misunderstanding. My usage example is using function fill_triangle not fill_triangle_on_window and I fixed the title.

2024-12-11 04:20 UTC, EthanRin requested changes
I've reviewed this PR and here are some changes suggestions:
- Update the for loop limit from 10 to 50 in the C# Top-Level example to match the rest of the implementations.
- Ensure that all of the Open Window names are consistent across all examples. I think calling it `Fill Triangle` is good. Especially since the other names used could be confused for other SplashKit functions with that name.

2024-12-11 09:53 UTC, EthanRin commented
@huyhuynh2319 If you could also change the window name for the python usage example, I'd love to approve this PR.

2024-12-11 11:23 UTC, huyhuynh2319 commented
I changed the name of the py code. Thanks for figuring it out.

2024-12-11 13:06 UTC, EthanRin commented
@huyhuynh2319 Hey mate, thanks for the update but you will still need to change the files name to match the function you're using as well as adding the numbering after the function name. Otherwise, your usage example won't show up on the site. Please also change the title and description of the text file accordingly and move the files to the fill_triangle folder rather than fill_triangle_on_window.

2025-02-17 12:06 UTC, closed without merging