Circle at
thoth-tech/splashkit.io-starlight pull request #317
Opened 2024-11-28 04:52 UTC by Jinx-means-jinx

# Overview
Add usage example circle at to show how to create a circle at a user-defined location with a specified radius.

Splashkit Function: `circle_at`

![image](https://github.com/user-attachments/assets/b167253c-f216-4e99-aab4-8fbd6e46148d)
![image](https://github.com/user-attachments/assets/3a8e4aa3-556d-48dd-8963-1f201d418024)

# Files Included
- [ ] Title and explanation (.txt)
- [ ] C++ code
- [ ] C# code (top-level statements)
- [ ] C# code (Object-Oriented Programming)
- [ ] Python code
- [ ] Screenshot

# Usage Example Checks
- [ ] Simple, clear demonstration of the function
- [ ] Code uses Splashkit functions
- [ ] Tested in Chrome and Firefox

2024-11-29 02:31 UTC, rmachu requested changes
I have reviewed this pull request and request some changes.

- The cpp program gets a random number for x while the other programs has a set number. This should be consistent across all files.
- You can use circle _A_  as a parameter in draw circle instead of the x and y, this would demonstrate the function better and avoid unused variables.

Other than this everything else looks good.

2024-12-14 21:45 UTC, ShaunR1991 approved these changes
Functionally the code works as expected. It looks like the update you made to the code from the previous review has one comment in your C++ file that is leftover from your previous implementation:

    //Give random  x_position value bewteen 200 - 400
    
Recommend adjusting that to be consistent with the other code files and to reflect what the code is doing. Otherwise, a solid usage example.

2025-01-04 05:28 UTC, Jinx-means-jinx commented
Fixed

2025-01-31 07:42 UTC, omckeon commented
Closing due to incorrect function being used (this is "circle_at_from_points"), as well as the example being too simple.

2025-01-31 07:42 UTC, closed without merging