Center point
thoth-tech/splashkit.io-starlight pull request #318
Opened 2024-11-28 11:13 UTC by Jinx-means-jinx

# Overview
Add new usage example and show how to find the center point for circles.

Splashkit Function: `center_point`

# Files Included
- [ ] Title and explanation (.txt)
- [ ] C++ code
- [ ] C# code (top-level statements)
- [ ] C# code (Object-Oriented Programming)
- [ ] Python code
- [ ] Screenshot

# Usage Example Checks
- [ ] Simple, clear demonstration of the function
- [ ] Code uses Splashkit functions
- [ ] Tested in Chrome and Firefox

2024-11-30 00:46 UTC, ctrlvish approved these changes
I've reviewed the `center_point` function usage examples
- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

2024-12-07 01:44 UTC, breezy-codes requested changes
I've left some minor requests for changes.

2024-12-07 01:44 UTC, breezy-codes commented on public/usage-examples/geometry/center_point/center_point-1-simple-oop.cs
> +        // Print result on window
There should be a blank line above the code comment.

2024-12-07 01:44 UTC, breezy-codes commented on public/usage-examples/geometry/center_point/center_point-1-simple-top-level.cs
> +// Print result on window
There should be a blank line above the code comment.

2024-12-07 01:44 UTC, breezy-codes commented on public/usage-examples/geometry/center_point/center_point-1-simple.cpp
> +    //Print result on window
There should be a blank line above the code comment.

2024-12-07 01:44 UTC, breezy-codes commented on public/usage-examples/geometry/center_point/center_point-1-simple.py
> +# Draw Point in the center of the circle
There should be a blank line above the code comment.

2024-12-07 01:44 UTC, breezy-codes commented on public/usage-examples/geometry/center_point/center_point-1-simple.py
> +# Print result on window
In all other code versions you put the code comment-
`# Print result on window` 
below the line-
`text = "Center Point At: (" + str(center.x) + ", " + str(center.y) + ")"`

Can you please modify the python version to be the same?

2024-12-07 01:44 UTC, breezy-codes commented on public/usage-examples/geometry/center_point/center_point-1-simple.txt
> +The following code shows examples of using [Center Point](/api/geometry/#center-point) to show how to use center point as origin point to cut circle.
Should be "shows an example of"

2025-01-30 13:52 UTC, omckeon commented
The python code is not using the function...

This happens to be due to an issue with a sprite function with the same name, which should have been brought up during the trimester...

2025-01-30 13:52 UTC, closed without merging