Review resources guide and improvement
thoth-tech/splashkit.io-starlight pull request #319
Opened 2024-11-29 23:35 UTC by ctrlvish

# Description

Checked:

- [x] The tutorial includes C#, C++, and Python.
- [x] No code errors were found.
- [x] The tutorial is clear to follow.
- [x] No spelling errors.

Changes Made:

1. Added the resource bundle initialisation step at the start.
2. Included code examples for loading a resource bundle and freeing it, with links to the relevant functions.
3. Attached a downloadable resource bundle for users to test.

## Type of change

_Please delete options that are not relevant._

- [x] Documentation (update or new)

## How Has This Been Tested?

I ran the code locally and manually tested the steps to ensure everything works as expected. I verified the existing steps by cross-referencing with the API documentation

## Testing Checklist

- [x] Tested in latest Chrome
- [x] Tested in latest Firefox
- [x] npm run build
- [ ] npm run preview

## Checklist

_Please delete options that are not relevant._

### If involving code

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Folders and Files Added/Modified

- Added:
  - [x] `/resources/guides/resource-bundles/basics/BasicBitmapResources.zip`
  - [x] `Resource-Bundles/images/output.png`
- Modified:
  - [x] 0-loading-resources-with-bundles.mdx

2024-12-05 07:11 UTC, breezy-codes requested changes
Fantastic update to this, its great you noticed an issue with the missing command for how to actually load resources and you've now added it in.

The demonstration is also great, and code runs correctly free of any errors. That could also be a great turned into a usage example for resource bundles to highlight this code further to help in using and loading resources.


I just have a couple small formatting requests but after those are done I'm happy to approve this.

2024-12-05 07:11 UTC, breezy-codes commented on src/content/docs/guides/Resource-Bundles/0-loading-resources-with-bundles.mdx
> +// Load resources from a file
It would be good to put a blank line above this, just for better formatting.

2024-12-05 07:11 UTC, breezy-codes commented on src/content/docs/guides/Resource-Bundles/0-loading-resources-with-bundles.mdx
> +      // Load resources from a file
Same here

2024-12-05 07:11 UTC, breezy-codes commented on src/content/docs/guides/Resource-Bundles/0-loading-resources-with-bundles.mdx
> +  // Load resources from a file
and here too

2024-12-05 07:11 UTC, breezy-codes commented on src/content/docs/guides/Resource-Bundles/0-loading-resources-with-bundles.mdx
> +# Load resources from a file
as well as here

2024-12-06 02:55 UTC, ctrlvish commented
Hi @breezy-codes, I have made the requested changes.

2024-12-06 03:16 UTC, breezy-codes approved these changes
Thanks for the changes, I now approve this PR

2025-01-31 10:16 UTC, merged