Circle intersect
thoth-tech/splashkit.io-starlight pull request #335
Opened 2024-12-08 09:46 UTC by Jinx-means-jinx

# Overview
New usage example to show how to detect if two circle A and B intersect or not.

Splashkit Function: `circles_intersect`
![image](https://github.com/user-attachments/assets/ab4ca5ba-295f-4d3c-8bc7-383ba9192334)
![image](https://github.com/user-attachments/assets/2caef5dc-59a2-4113-8d4d-274085f36a94)
![image](https://github.com/user-attachments/assets/6b7b1b1a-b1a6-4c7e-be9e-26a30e56411e)

# Files Included
- [ ] Title and explanation (.txt)
- [ ] C++ code
- [ ] C# code (top-level statements)
- [ ] C# code (Object-Oriented Programming)
- [ ] Python code
- [ ] Screenshot

# Usage Example Checks
- [ ] Simple, clear demonstration of the function
- [ ] Code uses Splashkit functions
- [ ] Tested in Chrome and Firefox

2024-12-11 01:02 UTC, SimonRhook requested changes
I've left some comments across the files requesting some small changes for code comments and just some wording updates for clarity. The comments I have left on the top level file for language update should be applied across all files.

Overall the program does a good job of demonstrating the circle_intersect function and I like that the users have to make their own circles. 

Once you have made these changes I'm happy to approve this PR

2024-12-12 03:41 UTC, Jinx-means-jinx commented
Fixed thanks

2024-12-12 04:48 UTC, SimonRhook approved these changes
Nice work, with the update per my recommendations I approve this PR.

- [x] All required files are present.
  - [x] Title and explanation (.txt)
  - [x] C++ code
  - [x] C# code (top-level statements)
  - [x] C# code (Object-Oriented Programming)
  - [x] Python code
- [x] Code correctly uses Splashkit functions.
- [x] Code clearly demonstrates the function.
- [x] All versions maintain the same structure and comments.
- [x] C++ code ran correctly.
- [x] C# top level code ran correctly.
- [x] C# OOP code ran correctly.
- [x] Python code ran correctly.

2024-12-14 21:42 UTC, ShaunR1991 approved these changes
A great idea for a program. Functionally the code works as expected, however two things to update:

Change the spelling of "Radient" to "Radius"
Recommend changing the colour of one of the circles to a different colour, say one red and one blue. This will help to differentiate between the two objects on the screen, since you only get 4 seconds of window time to determine the overlap. 
Lastly, I would recommend perhaps using a fill_circle method rather than draw_circle  to really demonstrate the overlap. 

Otherwise, good usage example!

2025-01-04 05:23 UTC, Jinx-means-jinx commented
All problem fixed, but I feel draw circle is better to show the two circles intersection.

2025-01-31 07:51 UTC, omckeon commented
Closing due to poor variable naming and that the example is using terminal input for a graphics window based function.

2025-01-31 07:51 UTC, closed without merging