Added various beyond SK programs
thoth-tech/splashkit.io-starlight pull request #338
Opened 2024-12-10 00:49 UTC by SimonRhook

# Description
Added various programs to compare SplashKit vs No SplashKit. These programs demonstrate the abstraction that takes place within the SplashKit SDK to hide away complexity. The No SplashKit versions essentially show what is happening in the back end of SplashKit when various functions are called. 
## Type of change

_Please delete options that are not relevant._

- [x] Addition of cpp code files

## How Has This Been Tested?

Programs have all been compiled and run to ensure they work.

## Testing Checklist

- [x] Tested in latest Chrome
- [x] Tested in latest Firefox
- [x] npm run build
- [x] npm run preview

## Checklist

_Please delete options that are not relevant._

### If involving code

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings

## Folders and Files Added/Modified

_Please list the folders and files added/modified with this pull request and delete options that are not relevant._

- Added:
  - [x] beyond-splashkit/Audio
  - [x] beyond-splashkit/InputValidation

## Additional Notes

Changes to not currently display on build. The goal is to integrate them into an actual guide at a later date.

2024-12-12 08:07 UTC, matt439 requested changes
I think this guide is a great idea! My personal experience after SIT102 was that I wanted to learn more about how I could make my own games without SplashKit. However, all the source code is abstracted away, which felt like a brick wall. I would have found this guide extremely useful as I tried to understand what it takes to draw graphics to the screen.

In terms of review, I only found some minor issues regarding formatting and value types. I have no doubt that this guide will help out many students who are looking to learn lower level coding.

2024-12-12 08:07 UTC, matt439 commented on src/content/docs/beyond-splashkit/InputValidation/int_input_validation.cpp
> +    while (! nosk_is_integer(x))
Space after exclamation point is inconsistent with 3 lines below.

2024-12-12 09:36 UTC, SimonRhook commented on src/content/docs/beyond-splashkit/Audio/Audio.mdx
> +    float volume = 0.5;
This is really interesting, for some reason my splashkit install has this function as float. 
![image](https://github.com/user-attachments/assets/34cbe900-0877-42f4-ada8-c1237a665e4c)
I originally declared volume to be double and got a typecast error which lead me to changing the variable to float.

2024-12-12 22:14 UTC, matt439 commented on src/content/docs/beyond-splashkit/Audio/Audio.mdx
> +    float volume = 0.5;
Hmm that is strange. I copied your code into the up-to-date splashkit-core repo:
![image](https://github.com/user-attachments/assets/19a93838-b307-4d92-a93b-0019605f7cde)

In `sound.h` I've got it as double:
![image](https://github.com/user-attachments/assets/5b8737bd-5f64-47ce-82c9-ea6dd471322c)

2024-12-12 22:17 UTC, SimonRhook commented on src/content/docs/beyond-splashkit/Audio/Audio.mdx
> +    float volume = 0.5;
I did discuss this with Olivia and its a known issue. I will push the change as double is supposed to be correct

2024-12-13 01:23 UTC, matt439 approved these changes
All issues are now resolved. Looks great!

2024-12-15 09:33 UTC, rmachu approved these changes
After the change, I approve this PR. Everything looks good.

2024-12-17 07:37 UTC, omckeon approved these changes
I have made some changes to these guides to provide some set up instructions and updated the code into tabs and individual code files (to prepare for SK Online).

These programs were really well done, and the eye dropper program is really useful to see it all come together!

2024-12-17 07:37 UTC, merged