5 Usage example for Graphics P3
thoth-tech/splashkit.io-starlight pull request #345
Opened 2024-12-12 04:12 UTC by huyhuynh2319

# Description
This is a usage example of the function display details, name, width, height and draw pixel on window.

Splashkit Function: 
`display-details`
`display-name`
`display-width`
`display-height`
`draw-pixel-on-window`
# Testing Checklist
- [x]  C++ code
- [x]  C# code (top-level statements)
- [x]  C# code (Object-Oriented Programming)
- [x]  Python code
- [x]  Screenshot
- [x]  Title and explanation (.txt)

# Usage Example Checks

- [x]  Simple, clear demonstration of the function
- [x]  Code uses Splashkit functions
- [x]  Tested in Chrome and Firefox

2024-12-13 02:17 UTC, rmachu requested changes
Hi! I have reviewed this pull request and suggest changes. Mostly with font, comments and spacing inconsistencies that apply to all the display functions programs. The draw pixel program is making the program go unresponsive when I tested it so I have suggested some changes there to help avoid the overload.

2024-12-13 02:17 UTC, rmachu commented on public/usage-examples/graphics/display_height/display-height-1-simple.cpp
> +        display disp = display_details(i); // Get the height of the display
Different loop comments.

2024-12-13 02:17 UTC, rmachu commented on public/usage-examples/graphics/draw_pixel_on_window/draw-pixel-on-window-1-simple.cpp
> +            draw_pixel_on_window(COLOR_GRAY, rnd(800), rnd(600));
Error in parameters. There should be a window parameter as well.

2024-12-13 02:17 UTC, rmachu commented on public/usage-examples/graphics/draw_pixel_on_window/draw-pixel-on-window-1-simple.cpp
> +    close_all_windows;
Missing '()' for function.

2024-12-13 02:17 UTC, rmachu commented on public/usage-examples/graphics/draw_pixel_on_window/draw-pixel-on-window-1-simple.cpp
> +    while (!quit_requested())
This caused the program to go unresponsive. I suggest removing this while loop and increase the number of pixels.

2025-03-14 04:57 UTC, omckeon commented
These examples are not showing the usefulness of the functions very well, so will close this PR.
Only 1 example per PR for future PRs.

2025-03-14 04:57 UTC, closed without merging