polish the new SK website
thoth-tech/splashkit.io-starlight pull request #7
Opened 2023-12-06 04:32 UTC by queser9

# Description
 
1，added social media hyperlinks and icon in the footer
2 ，make the icon responsive to theme changes
3 ，added the hyperlinks to out core team and contributors
 
## Changes Made

 
# How Has This Been Tested?
 
## Testing Checklist:

- [x] Prettier
- [x] Vale
 
# Checklist
 
Please make sure you have completed the following before merging this pull request:
 
- [x] My submission follows the style guidelines of this project
- [x] My submission is based on the relevant template in `Instructions and Templates/`
- [x] My tutorial is based on an approved tutorial proposal
- [x] I have requested a review from Seniors on the Pull Request

2023-12-06 04:33 UTC, queser9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Landing Page Footer and Add Facebook Icon](https://trello.com/c/fky6r3uc/320-update-landing-page-footer-and-add-facebook-icon)

2023-12-12 07:42 UTC, omckeon commented
Resolve conflicts, and then you can move the Trello card into Mentor review

2023-12-13 04:51 UTC, omckeon commented on astro.config.mjs
SplashKit does not have a facebook page, so this is not needed. I would also suggest removing twitter, as the account is not being used anymore it seems.

2023-12-13 04:51 UTC, omckeon commented on src/components/social.astro
SplashKit does not have a facebook page, so this is not needed. I would also suggest removing twitter, as the account is not being used anymore it seems.

2023-12-13 04:52 UTC, omckeon commented on src/content/docs/index.mdx
SplashKit does not have a facebook page, so this is not needed. I would also suggest removing twitter, as the account is not being used anymore it seems.

The links in the footer are good though.

2023-12-13 04:56 UTC, omckeon commented on src/styles/custom.css
As the icons are included in the top right corner of the page, these icons are not needed.

2023-12-13 04:58 UTC, omckeon requested changes
See the comments in each file to see the changes requested.
Also, make sure to do 'git pull' before updating, as there seemed to be some old code when I tested these changes.

2023-12-13 10:23 UTC, omckeon commented
Closing this PR to simplify changes.

2023-12-13 10:23 UTC, closed without merging